# name: Update Classroom Status

# on:
#   workflow_dispatch: # 手動実行を許可
#   schedule:
#     # 日本時間の平日9:00-17:50の間、10分ごとに実行
#     # (UTCでは 0:00-8:50 になります)
#     - cron: '*/10 0-8 * * 1-5'

# jobs:
#   update-status-job:
#     runs-on: ubuntu-latest
#     permissions:
#       # リポジトリへの書き込み権限
#       contents: write
#     steps:
#       - name: 1. Checkout Repository
#         uses: actions/checkout@v4

#       - name: 2. Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: 3. Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests pandas numpy pytz gspread gspread-dataframe

#       - name: 4. Run Status Update Script
#         # GitHub Secretsに設定した値を環境変数としてスクリプトに渡す
#         env:
#           GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
#           SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
#         run: python main.py

#       - name: 5. Commit and Push new status.json
#         uses: stefanzweifel/git-auto-commit-action@v5
#         with:
#           commit_message: "Update classroom status data"
#           # 更新対象のファイル名を指定
#           file_pattern: 'status.json'
